# -*- coding: utf-8 -*-
"""Painel Streamlit (Versão Nuvem)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xL7mhEsJ8zSFlvrbmYiM8A_I2iX1lwvl
"""

import streamlit as st
import pandas as pd
import numpy as np
import xgboost as xgb
import joblib
import plotly.express as px
import os

# ==========================================
# CONFIGURAÇÃO GERAL E ESTILO CLEAN (CSS)
# ==========================================
st.set_page_config(page_title="CCO - Manutenção Preditiva", page_icon="🚜", layout="wide", initial_sidebar_state="expanded")

st.markdown("""
    <style>
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    div[data-testid="metric-container"] {
        background-color: #ffffff;
        border: 1px solid #e0e0e0;
        border-radius: 8px;
        padding: 15px 20px;
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.05);
    }
    .block-container {
        padding-top: 2rem;
        padding-bottom: 2rem;
    }
    </style>
""", unsafe_allow_html=True)

# ==========================================
# 1. FUNÇÕES DE CARREGAMENTO PARA A NUVEM
# ==========================================
@st.cache_resource
def carregar_modelo():
    # Agora lê do mesmo diretório onde está o app.py no GitHub
    modelo_path = 'modelo_xgboost_v8.pkl'
    if os.path.exists(modelo_path):
        return joblib.load(modelo_path)
    else:
        st.error("Erro: Ficheiro do modelo 'modelo_xgboost_v8.pkl' não encontrado no diretório.")
        return None

@st.cache_data
def carregar_dados_demo():
    # Na nuvem, carregamos uma base pré-processada leve em vez de processar do zero
    dados_path = 'dados_demo.csv'
    if os.path.exists(dados_path):
        return pd.read_csv(dados_path)
    else:
        st.error("Erro: Ficheiro de dados 'dados_demo.csv' não encontrado no diretório.")
        return pd.DataFrame()

# ==========================================
# 2. CONTROLES LATERAIS (SIDEBAR)
# ==========================================
st.sidebar.title("⚙️ Painel de Controle")
st.sidebar.markdown("Ajuste a sensibilidade da Inteligência Artificial e os parâmetros da operação.")

st.sidebar.subheader("Sensibilidade do Modelo")
corte = st.sidebar.slider("Ponto de Corte de Risco (%)", min_value=50, max_value=95, value=70, step=5)

st.sidebar.markdown("---")
st.sidebar.subheader("Parâmetros Financeiros")
custo_corretiva = st.sidebar.number_input("Custo de Quebra Crítica (R$)", value=150000, step=10000)
custo_preventiva = st.sidebar.number_input("Custo de Inspeção (R$)", value=3000, step=500)
tempo_corretiva = st.sidebar.number_input("Máquina Parada na Quebra (h)", value=24, step=2)
tempo_preventiva = st.sidebar.number_input("Máquina Parada na Inspeção (h)", value=2, step=1)

with st.spinner("Conectando ao sistema CCO em Nuvem..."):
    modelo = carregar_modelo()
    dados = carregar_dados_demo()

if modelo is not None and not dados.empty:
    features = ['Duracao_Ciclo_Minutos', 'Hora_Inicio', 'Dia_Semana', 'Sintomas_Ultimas_24H', 'Sintomas_Ultimas_4H', 'Sintomas_Ultimas_2H', 'Razao_Agravamento_4H', 'Aceleracao_Aguda_2H']

    # Executando a predição na nuvem
    probabilidades = modelo.predict_proba(dados[features].fillna(0))[:, 1]
    dados['Probabilidade_Quebra'] = probabilidades * 100
    alertas_ativos = dados[dados['Probabilidade_Quebra'] >= corte].copy()

    verdadeiros_positivos = len(alertas_ativos[alertas_ativos['Target_4H'] == 1])
    falsos_positivos = len(alertas_ativos[alertas_ativos['Target_4H'] == 0])
    falsos_negativos = len(dados[(dados['Probabilidade_Quebra'] < corte) & (dados['Target_4H'] == 1)])

    custo_sem_ia = (verdadeiros_positivos + falsos_negativos) * custo_corretiva
    custo_com_ia = (falsos_negativos * custo_corretiva) + (len(alertas_ativos) * custo_preventiva)
    economia = custo_sem_ia - custo_com_ia
    horas_salvas = ((verdadeiros_positivos + falsos_negativos) * tempo_corretiva) - ((falsos_negativos * tempo_corretiva) + (len(alertas_ativos) * tempo_preventiva))

    # ==========================================
    # 3. INTERFACE PRINCIPAL (VISUALIZAÇÃO)
    # ==========================================
    st.title("Centro de Controle Operacional (CCO)")
    st.markdown("Monitorização de frotas industriais orientada por **Inteligência Artificial (XGBoost)** em Nuvem.")
    st.write("")

    def formata_moeda(valor):
        return f"R$ {valor:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Economia Gerada", formata_moeda(economia))
    col2.metric("Disponibilidade Física", f"{horas_salvas} horas")
    col3.metric("Equipamentos Críticos", f"{len(alertas_ativos)}")
    col4.metric("Falsos Alarmes (Desperdício)", f"{falsos_positivos}", delta="Inspeções desnecessárias", delta_color="inverse")

    st.markdown("---")

    aba_geral, aba_diretoria, aba_oficina, aba_operacao = st.tabs(["🌐 Visão Geral", "💼 Diretoria Financeira", "🔧 Oficina", "🚜 Operação"])

    with aba_geral:
        st.subheader("Mapa de Risco da Frota")
        grafico_exec_df = alertas_ativos.groupby('TAG').agg({'Probabilidade_Quebra': 'mean', 'Sintomas_Ultimas_24H': 'count'}).reset_index().rename(columns={'Sintomas_Ultimas_24H': 'Volume_Alertas'})
        fig_exec = px.scatter(grafico_exec_df, x='Volume_Alertas', y='Probabilidade_Quebra', text='TAG', size='Probabilidade_Quebra', color='Probabilidade_Quebra', color_continuous_scale='Reds')
        fig_exec.update_traces(textposition='top center')
        fig_exec.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)")
        st.plotly_chart(fig_exec, use_container_width=True)

    with aba_diretoria:
        st.subheader("Análise de Retorno sobre Investimento (ROI)")
        col_f1, col_f2 = st.columns([1.5, 1])
        with col_f1:
            df_custos = pd.DataFrame({'Cenário Operacional': ['Tradicional (Sem IA)', 'Preditiva (Com IA)'], 'Custo Projetado (R$)': [custo_sem_ia, custo_com_ia]})
            fig_custos = px.bar(df_custos, x='Custo Projetado (R$)', y='Cenário Operacional', orientation='h', color='Cenário Operacional', color_discrete_sequence=['#E74C3C', '#2ECC71'], text='Custo Projetado (R$)')
            fig_custos.update_traces(texttemplate='R$ %{text:,.2f}'.replace(",", "X").replace(".", ",").replace("X", "."), textposition='inside')
            fig_custos.update_layout(showlegend=False, paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)")
            st.plotly_chart(fig_custos, use_container_width=True)

        with col_f2:
            st.info(f"O capital de **R$ {economia:,.2f}** foi protegido contra falhas catastróficas ao assumir o corte de risco em {corte}%.")

    with aba_oficina:
        st.subheader("Fila Urgente de Oficina")
        if not alertas_ativos.empty:
            alertas_ativos = alertas_ativos.sort_values(by='Probabilidade_Quebra', ascending=False)
            tabela_oficina = alertas_ativos[['TAG', 'Inicio', 'Probabilidade_Quebra', 'Sintomas_Ultimas_4H', 'Sintomas_Ultimas_2H', 'Aceleracao_Aguda_2H']].head(15)
            tabela_oficina.rename(columns={'Inicio': 'Ciclo', 'Probabilidade_Quebra': 'Risco', 'Aceleracao_Aguda_2H': 'Agravamento'}, inplace=True)
            tabela_oficina['Risco'] = tabela_oficina['Risco'].apply(lambda x: f"{x:.1f}%")
            tabela_oficina['Agravamento'] = tabela_oficina['Agravamento'].apply(lambda x: f"{x*100:.0f}%")
            st.dataframe(tabela_oficina, use_container_width=True, hide_index=True)
        else:
            st.success("Sem alertas críticos no limite definido.")

    with aba_operacao:
        col_op1, col_op2 = st.columns(2)
        with col_op1:
            st.subheader("Fadiga vs Risco")
            fig_scatter = px.scatter(dados.head(1500), x='Duracao_Ciclo_Minutos', y='Probabilidade_Quebra', color='Sintomas_Ultimas_2H', color_continuous_scale='Turbo')
            fig_scatter.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)")
            st.plotly_chart(fig_scatter, use_container_width=True)

        with col_op2:
            st.subheader("Comportamento do Modelo")
            importancias = modelo.feature_importances_ * 100
            df_imp = pd.DataFrame({'Variável': features, 'Peso (%)': importancias}).sort_values(by='Peso (%)', ascending=True)
            dicionario_vars = {'Sintomas_Ultimas_24H': 'Alertas Totais (24h)', 'Sintomas_Ultimas_4H': 'Alertas Recentes (4h)', 'Sintomas_Ultimas_2H': 'Alertas Críticos (2h)', 'Aceleracao_Aguda_2H': 'Velocidade de Degradação', 'Razao_Agravamento_4H': 'Histórico de Agravamento', 'Duracao_Ciclo_Minutos': 'Tempo de Operação', 'Dia_Semana': 'Dia', 'Hora_Inicio': 'Turno'}
            df_imp['Variável'] = df_imp['Variável'].map(dicionario_vars)
            fig_imp = px.bar(df_imp, x='Peso (%)', y='Variável', orientation='h', color='Peso (%)', color_continuous_scale='Blues')
            fig_imp.update_layout(showlegend=False, paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)")
            st.plotly_chart(fig_imp, use_container_width=True)